name: CD

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'rollup.config.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Verify build output
      run: |
        if [ ! -d "build" ]; then
          echo "Build directory not found"
          exit 1
        fi
        if [ ! -f "build/index.js" ]; then
          echo "Build file index.js not found"
          exit 1
        fi

    - name: Build Storybook
      run: npm run build-storybook
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
    
    - name: Publish to npm
      run: npm publish 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}