name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: npm install
    
    - name: Generate changelog
      run: |
        git fetch --prune --unshallow
        npx conventional-changelog-cli -p angular -i CHANGELOG.md -s
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
    
    - name: Bump version
      run: |
        npm version ${{ github.ref_name:1}}
        git push --follow-tags